name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Install root deps
        run: npm ci
      - name: Install client deps
        run: cd client && npm ci
      - name: Install server deps
        run: cd server && npm ci || true
      - name: Run migrations (dry, expect no DB)
        run: |
          node -e "try{require('./server/scripts/migrate.js')}catch(e){console.log('Skip migrate in CI (no DB)')}"
      - name: Lint placeholder
        run: node -e "console.log('Lint OK placeholder')"
